import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Links from '@/components/Links'
import Images from '@/components/Images'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="descri  ption" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>

          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/about.js</code>
          </p>

          <Images />

        </div>
        <Links />

      </main>
    </>
  )
}
